### ISSUE TITLE
video for Dmitry Vetrov - Introduction to Bayesian methods.

### ISSUE THREAD

**Issue by Sandy4321** [bayesgroup/deepbayes-2018#7]
may you share videos for other lectures, for example
Dmitry Vetrov - Introduction to Bayesian methods.
you share many slildes https://drive.google.com/drive/folders/1rJ-HTN3sNTvhJXPoXEEhfGlZWtjNY26C
not not all videos are available 

![image](https://user-images.githubusercontent.com/11426119/45265899-7c2bd280-b420-11e8-8b59-b65f33ebd587.png)

**Comment by artsobolev** [comment]
Unfortunately, video of the first lecture wasn't recorded properly and is lost forever. However, all other lectures are available.
